1

In [1]:
import numpy as np
arr = np.array([i for i in range(1,21)])
print("Array: ", arr)
print("Sum: ", np.sum(arr))
print("Mean: ", np.mean(arr))
print("Median: ", np.median(arr))
print("Standard Deviation: ", np.std(arr))




Array:  [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Sum:  210
Mean:  10.5
Median:  10.5
Standard Deviation:  5.766281297335398


Explanation:
- List comprehension is used to create the list of numbers
- numpy functions are used to compute sum, mean, median and standard deviation

In [2]:
print("Indices of the element greater than 10 are:")
print([i for i in range(len(arr)) if arr[i]>10])

Indices of the element greater than 10 are:
[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]


Explanation:
- indices of elements greater than 10 are fetched using list comprehension and then printed

2

In [3]:
arr = np.array([i for i in range(1,17)])
arr2 = np.reshape(arr,(4,4))
print(arr2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


Explanation:
- list created using list comprehension and then converted into numpy array.
- array reshaped using numpy function

In [4]:
print(arr2.T)

[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]


Explanation:
- np.array.T is used to create transpose of numpy array matrix

In [5]:
print("Row-wise Sum: ", np.sum(arr2, axis=1))
print("Column-wise Sum: ", np.sum(arr2, axis=0))

Row-wise Sum:  [10 26 42 58]
Column-wise Sum:  [28 32 36 40]


Explanation:
- np.sum is used along axis 0 to generate column wise sum and along axis 1 to generate row wise sum

3

In [6]:
arr3 = np.random.randint(1, 21, size=(3, 3))
arr4 = np.random.randint(1, 21, size=(3, 3))

print("First array: \n", arr3)
print("Second array: \n", arr4)

print("Addition of arrays:\n",arr3+arr4)
print("Subtraction of arrays:\n",arr3-arr4)
print("Multiplication of arrays:\n",arr3*arr4)
print("Dot product is same as Linear Multiplication.")

First array: 
 [[ 9  6 13]
 [ 6  7 17]
 [13 10  8]]
Second array: 
 [[17 14 17]
 [ 5 17 20]
 [ 6 20 20]]
Addition of arrays:
 [[26 20 30]
 [11 24 37]
 [19 30 28]]
Subtraction of arrays:
 [[ -8  -8  -4]
 [  1 -10  -3]
 [  7 -10 -12]]
Multiplication of arrays:
 [[153  84 221]
 [ 30 119 340]
 [ 78 200 160]]
Dot product is same as Linear Multiplication.


Explanation:
- np.random.randint generates random integers within given range and given shape
- mathematical binary operators are used to carry out linear operations

In [7]:
print("Cross product of arrays:\n",np.dot(arr3,arr4))

Cross product of arrays:
 [[261 488 533]
 [239 543 582]
 [319 512 581]]


Explanation:
- np.dot function is used to generate the cross product of matrix. In matrix the dot product is same as linear multiplication.

4

In [8]:
arr_1d = np.arange(12)
print("1d Array:\n",arr_1d)
reshaped = arr_1d.reshape(3, 4)
print("Reshaped Array:\n",reshaped)
result = reshaped[:2, -2:]
print("Sliced Array:\n",result)

1d Array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped Array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Sliced Array:
 [[2 3]
 [6 7]]


Explanation:
- np.arange returns all elements in given range nas an array
- array is reshaped and sliced as said