1

In [1]:
import numpy as np
arr = np.array([i for i in range(1,21)])
print("Array: ", arr)
print("Sum: ", np.sum(arr))
print("Mean: ", np.mean(arr))
print("Median: ", np.median(arr))
print("Standard Deviation: ", np.std(arr))




Array:  [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Sum:  210
Mean:  10.5
Median:  10.5
Standard Deviation:  5.766281297335398
indices of the element greater than 10 are:
[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]


In [2]:
print("Indices of the element greater than 10 are:")
print([i for i in range(len(arr)) if arr[i]>10])

indices of the element greater than 10 are:
[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]


2

In [6]:
arr = np.array([i for i in range(1,17)])
arr2 = np.reshape(arr,(4,4))
print(arr2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [7]:
print(arr2.T)

[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]


In [11]:
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [13]:
print("Row-wise Sum: ", np.sum(arr2, axis=1))
print("Column-wise Sum: ", np.sum(arr2, axis=0))

Row-wise Sum:  [10 26 42 58]
Column-wise Sum:  [28 32 36 40]


3

In [17]:
arr3 = np.random.randint(1, 21, size=(3, 3))
arr4 = np.random.randint(1, 21, size=(3, 3))

print("First array: \n", arr3)
print("Second array: \n", arr4)

print("Addition of arrays:\n",arr3+arr4)
print("Subtraction of arrays:\n",arr3-arr4)
print("Multiplication of arrays:\n",arr3*arr4)
print("Dot product is same as Linear Multiplication.")

First array: 
 [[ 2 12 18]
 [16 13 10]
 [18  8  3]]
Second array: 
 [[19 17 11]
 [16  3  6]
 [ 7  8 20]]
Addition of arrays:
 [[21 29 29]
 [32 16 16]
 [25 16 23]]
Subtraction of arrays:
 [[-17  -5   7]
 [  0  10   4]
 [ 11   0 -17]]
Multiplication of arrays:
 [[ 38 204 198]
 [256  39  60]
 [126  64  60]]
Dot product is same as Linear Multiplication.


In [18]:
print("Cross product of arrays:\n",np.dot(arr3,arr4))

Cross product of arrays:
 [[356 214 454]
 [582 391 454]
 [491 354 306]]


4

In [21]:
arr_1d = np.arange(12)
print("1d Array:\n",arr_1d)
reshaped = arr_1d.reshape(3, 4)
print("Reshaped Array:\n",reshaped)
result = reshaped[:2, -2:]
print("Sliced Array:\n",result)

1d Array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped Array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Sliced Array:
 [[2 3]
 [6 7]]
